name: PR Tests

on:
  pull_request:
    branches: [ main, nishant/page-extension-setup ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'demo/src/**'
      - 'demo/src/tests/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'jest.config.js'
      - 'playwright.config.ts'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install demo dependencies
      run: |
        cd demo
        npm ci
        
    - name: Build package
      run: npm run build
      
    - name: Run unit tests
      run: npm test
      
    - name: Run demo tests
      run: |
        cd demo
        npm run test:ci
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-node-${{ matrix.node-version }}
        path: |
          demo/test-results/
          demo/playwright-report/
        retention-days: 7

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npx eslint src/ --ext .ts,.tsx --max-warnings 0
      
    - name: Run TypeScript check
      run: npx tsc --noEmit
      
    - name: Check package.json
      run: npm pkg fix --dry-run

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level moderate
      
    - name: Install demo dependencies
      run: |
        cd demo
        npm ci
        
    - name: Run demo security audit
      run: |
        cd demo
        npm audit --audit-level moderate

  build-check:
    name: Build Verification
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build package
      run: npm run build
      
    - name: Verify build output
      run: |
        if [ ! -d "dist" ]; then
          echo "Build failed: dist directory not found"
          exit 1
        fi
        
        if [ ! -f "dist/index.js" ]; then
          echo "Build failed: dist/index.js not found"
          exit 1
        fi
        
        if [ ! -f "dist/index.d.ts" ]; then
          echo "Build failed: dist/index.d.ts not found"
          exit 1
        fi
        
        echo "Build verification successful"
        
    - name: Check package size
      run: |
        PACKAGE_SIZE=$(du -s dist | cut -f1)
        echo "Package size: ${PACKAGE_SIZE}KB"
        
        if [ $PACKAGE_SIZE -gt 500 ]; then
          echo "Warning: Package size is larger than 500KB"
        fi
